services:
  app:
    build: ./flaskAPP
    ports:
      - 5000:5000
    volumes:
      - ./flaskAPP:/app
    environment:
      FLASK_DEBUG: 1
    command: flask run -h 0.0.0.0
    env_file:
      - .env
  db:
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - ./database:/docker-entrypoint-initdb.d